all: src/velocidadAccesoCache.cpp src/alineoMemoria.cpp src/multiplicacionMatrices.cpp src/prefetchSoftware.cpp src/prefetchHardware.cpp
	g++ -O0 src/velocidadAccesoCache.cpp -o obj/velocidadAccesoCache
	g++ -O0 src/alineoMemoria.cpp -o obj/alineoMemoria
	g++ -O0 src/multiplicacionMatrices.cpp -o obj/multiplicacionMatrices
	g++ -O0 src/prefetchSoftware.cpp -o obj/prefetchSoftware
	g++ -O0 src/prefetchHardware.cpp -o obj/prefetchHardware

clean:
	rm -f obj/*